language: cpp
compiler: clang

sudo: false
dist: trusty

os: linux

install: 
 - wget http://www.cmake.org/files/v3.2/cmake-3.2.0-Linux-x86_64.tar.gz
 - tar -xzf cmake-3.2.0-Linux-x86_64.tar.gz
 

script: 
 - mkdir build && cd build
 - ../cmake-3.2.0-Linux-x86_64/bin/cmake ..
 - make
 - cd ..
 - mv project_test.cmake build/
 - mv CTestConfig.cmake build/
 - cd build
 - ctest -VV -S project_test.cmake
