language: cpp
compiler: clang

sudo: false
dist: trusty

os: linux

install: 
 - wget http://www.cmake.org/files/v3.2/cmake-3.2.2.tar.gz
 - tar xf cmake-3.2.2.tar.gz
 - cd cmake-3.2.2
 - ./configure
 - make

script: 
 - mkdir build && cd build
 - cmake ..
 - make
 - ctest -S ../build.cmake
